# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{blammo}
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Bassett"]
  s.date = %q{2010-06-10}
  s.default_executable = %q{blam}
  s.description = %q{      Changelog generator.
}
  s.email = %q{josh.bassett@gmail.com}
  s.executables = ["blam"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".bundle/config",
     ".gitignore",
     "Gemfile",
     "README.md",
     "Rakefile",
     "VERSION",
     "bin/blam",
     "lib/blammo.rb",
     "lib/blammo/alone.rb",
     "lib/blammo/changelog.rb",
     "lib/blammo/cli.rb",
     "lib/blammo/commit.rb",
     "lib/blammo/git.rb",
     "lib/blammo/release.rb",
     "lib/core_ext/blank.rb",
     "spec/blammo/changelog_spec.rb",
     "spec/blammo/cli_spec.rb",
     "spec/blammo/commit_spec.rb",
     "spec/blammo/git_spec.rb",
     "spec/blammo/release_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "templates/changelog.html.erb"
  ]
  s.homepage = %q{http://github.com/nullobject/blammo}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{CHANGELOG from Blammo.}
  s.test_files = [
    "spec/blammo/changelog_spec.rb",
     "spec/blammo/cli_spec.rb",
     "spec/blammo/commit_spec.rb",
     "spec/blammo/git_spec.rb",
     "spec/blammo/release_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<git>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_development_dependency(%q<hirb>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rr>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<timecop>, [">= 0"])
    else
      s.add_dependency(%q<git>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<hirb>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rr>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<timecop>, [">= 0"])
    end
  else
    s.add_dependency(%q<git>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<hirb>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rr>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<timecop>, [">= 0"])
  end
end

